import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component WorkspaceButton inherits Button {
    width: 28px;
    height: 28px;
}

export component WorkspaceIndicator inherits Rectangle {
    background: #313244;
    border-radius: 8px;

    in-out property <int> current-workspace: 1;

    HorizontalBox {
        padding: 8px;
        spacing: 4px;

        WorkspaceButton {
            text: "1";
            clicked => { root.current-workspace = 1; }
        }

        WorkspaceButton {
            text: "2";
            clicked => { root.current-workspace = 2; }
        }

        WorkspaceButton {
            text: "3";
            clicked => { root.current-workspace = 3; }
        }

        WorkspaceButton {
            text: "4";
            clicked => { root.current-workspace = 4; }
        }
    }
}
